Entity:
  ssn:
    type: CARDINAL
    methods:
      ner:
  state:
    type: 
      - ZIPCODE
      - AP/LOCATION
    methods:
      ner:
  birthday:
    type: DATE
    methods:
      ner:
  appt_date:
    type: DATE
    methods:
      ner:
  appt_time:
    type: TIME
    methods:
      ner:
  department:
    type: PICKLIST
    methods:
      fuzzy_matching:
        - Therapist
        - Doctor
    suggest_value: yes
  providers_name:
    type: PERSON
    methods:
      ner:
      # spelling:
  name:
    type: PERSON
    methods:
      ner:
      # spelling:
  covid_protocol:
    methods:
  have_health_insurance:
    type: USER_UTT
    methods:
      user_utterance:
