Flag: # within one turn
  - got_info
  - polarity
  - max_no_info_turn
  - continuous_no_info_turn
  - got_intent
  - got_entity_info

State: # between turns
  - cur_task
  - confirm_continue
  - confirm_entity
  - confirm_intent
  - cur_entity_name

Logic:
  - "not got_info":
      - "confirm_intent":
          - task_confirm_handler
      - "confirm_entity":  # confirm entity w/o info
          - entity_confirm_handler
      - "not cur_task":
          - "confirm_continue":
              - "polarity == 1":
                  - greetings
              - "polarity == -1":
                  - goodbye
          - "polarity == 0":
              - "continuous_no_info_turn > max_no_info_turn":
                  - goodbye
              - greetings
          - "polarity == 1":
              - empty_response
          - "polarity == -1":
              - empty_response
      - "cur_entity_name":
          - "polarity == 1":
              - empty_response
          - fail_entity
  - got_info:
      - "confirm_intent":
          - task_confirm_handler
      - "confirm_entity":  # confirm entity w/ info
          - entity_confirm_handler
      - "got_intent and got_entity_info":
          - got_new_task
      - "got_intent":
          - got_new_task
      - "got_entity_info":
          - entity_info_handler
