Entity Extraction:
  CARDINAL:
    ner:
  DATE:
    ner:
  EMAIL:
    ner:
    spelling:
  EVENT:
    ner:
  FAC:
    ner:
  LANGUAGE:
    ner:
  LAW:
    ner:
  AP/LOCATION:
    ner:
  MONEY:
    ner:
  NORP:
    ner:
  ORDINAL:
    ner:
  ORG:
    ner:
  PERCENT:
    ner:
  PERSON:
    ner:
  DUCKLING/phone-number:
    ner:
  PICKLIST:
    fuzzy_matching:
  PRODUCT:
    ner:
  QUANTITY:
    ner:
  TIME:
    ner:
  USER_UTT:
    user_utterance:
  DUCKLING/url:
    ner:
  WORK_OF_ART:
    ner:
  ZIPCODE:
    ner:
    spelling:
