Flag: # within one turn
  - got_info
  - polarity
  - got_intent
  - got_entity_info

State: # between turns
  - cur_task
  - confirm_continue
  - confirm_entity
  - confirm_intent
  - cur_entity_name
  - max_no_info_turn
  - continuous_no_info_turn
  - multiple_entities

Logic:
  - "not got_info":
      - "confirm_intent": # continuous no info turn
          - task_confirm_handler
      - "confirm_entity":  # confirm entity w/o info, continuous no info turn
          - entity_confirm_handler
      - "not cur_task":
          - "confirm_continue":
              - "polarity == 1":
                  - greetings
              - "polarity == -1":
                  - goodbye
          - "continuous_no_info_turn > max_no_info_turn":
              - forward_to_human
          - empty_response # continuous no info turn
      - "cur_entity_name": # continuous no info turn
          - "polarity == -1":
              - "multiple_entities":
                  - no_entity_candidate_selected
              - fail_entity
          - "continuous_no_info_turn > max_no_info_turn":
              - fail_entity
          - empty_response
  - got_info:
      - "confirm_intent":
          - task_confirm_handler
      - "confirm_entity":  # confirm entity w/ info
          - entity_confirm_handler
      - "got_intent and got_entity_info":
          - new_task_with_info
      - "got_intent":
          - got_new_task
      - "got_entity_info":
          - entity_info_handler
